swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/LoginRequest'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/LoginApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/account/{accountId}:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Account API
      description: API for fetching a user account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: User Account Request Payload
          required: true
          schema:
            $ref: '#/definitions/AccountRequest'
      produces:
        - application/json
      responses:
        '200':
          description: User account retrieved Successfully
          schema:
            $ref: '#/definitions/UserAccountResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/account/{accountId}/{transactionId}:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User transaction API
      description: API for fetching a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Transaction Request Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionRequest'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved Successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Account API
      description: API for updating transaction details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user transaction details
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdateRequest'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved Successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error



securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  
  LoginRequest:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  
  LoginApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  
  UserProfileResponse:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      accounts:
        type: array
        items:
          $ref: '#/definitions/AccountShort'
        
  AccountShort:
    type: object
    properties:
      id:
        type: string
      accountType: 
        type: string
      balance:
        type: string

  AccountRequest:
    properties:
        token:
          type: string
        accountId:
          type: string
          description: account id

  UserAccountResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          accountType: 
              type: string
          balance:
              type: string
          transactionsRange:
              type: string
          transactions:
              type: array
              items:
                $ref: '#/definitions/Transaction'
  
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      transactionType:
        type: string
      category:
        type: string
      description:
        type: string
      amount:
        type: string
      notes: 
        type: string

  TransactionRequest:
    properties:
        token:
          type: string
        accountId:
          type: string
          description: account id
        transactionId:
          type: string
          description: transaction id
  
  TransactionUpdateRequest:
    properties:
        token:
          type: string
        accountId:
          type: string
          description: account id
        transactionId:
          type: string
          description: transaction id
        notes:
          type: string
        category:
          type: string


  TransactionResponse:        
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          date:
            type: string
          transactionType:
            type: string
          category:
            type: string
          description:
            type: string
          amount:
            type: string
          notes: 
            type: string


